name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.9.0]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    # You can include deployment steps here if desired, e.g.,
    # deploying to a server or cloud function
    # - name: Deploy to Server
    #   run: |
    #     ssh user@yourserver "cd /path/to/app && git pull && npm install && pm2 restart your-app"
