name: Run Python App

on: 
  push: 
    branches: 
      - main  # Change to the branch you want to trigger the workflow on
  pull_request: 
    branches: 
      - main  # Change to the branch you want to trigger the workflow on

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify your required Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure you have a requirements.txt for your dependencies

      - name: Run app.py
        run: python app.py
