name: Run Python App

on: 
  push: 
    branches: 
      - main  # Adjust as needed
  pull_request: 
    branches: 
      - main  # Adjust as needed

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Replace with your required Python version

      - name: Run app.py
        run: python app.py
