name: Flask App

on:
  push:
    branches:
      - main  # or your target branch
  pull_request:
    branches:
      - main  # or your target branch

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run app.py
        run: python app.py
